name: Code styles, tests and building
on:
  pull_request:
    branches:
      - main
      - develop
      - ketryn-desafio
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - run: cd ./githubapi-frontend && npm install
      - run: cd ./githubapi-frontend && npm run lint
      - run: cd ./githubapi-frontend && npm run test
      - run: cd ./githubapi-frontend && npm run build
    env:
      CI: true